# Generated by Django 4.1.1 on 2022-10-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=40)),
                ('founded', models.IntegerField()),
                ('genre', models.CharField(choices=[('NO GENRE', 'No genre'), ('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('ELECTRONIC', 'Electronic'), ('DISCO', 'Disco'), ('R&B', 'Rhythm and Blues'), ('COUNTRY', 'Country'), ('POP', 'Pop'), ('NEW AGE', 'New age'), ('METAL', 'Metal')], default='No genre', max_length=14)),
            ],
        ),
    ]
