# Generated by Django 4.1.1 on 2022-10-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_band_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('NO GENRE', 'No genre'), ('INDUSTRIAL', 'Industrial'), ('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('ELECTRONIC', 'Electronic'), ('DISCO', 'Disco'), ('R&B', 'Rhythm and Blues'), ('COUNTRY', 'Country'), ('POP', 'Pop'), ('NEW AGE', 'New age'), ('METAL', 'Metal')], default='No genre', max_length=14),
        ),
    ]
