# Generated by Django 4.1.1 on 2022-10-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='release',
            new_name='release_date',
        ),
    ]
