# Generated by Django 4.1.1 on 2022-10-12 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0006_band_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='music_app.band'),
        ),
    ]
