# Generated by Django 4.1.1 on 2022-10-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0008_alter_album_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
