# Generated by Django 4.1.1 on 2022-10-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0009_album_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('length', models.FloatField(default=1.0)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
