# Generated by Django 4.1.1 on 2022-10-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0012_alter_album_group_alter_album_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='tracks',
        ),
    ]
