# Generated by Django 4.1.1 on 2022-10-12 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0013_remove_album_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='albums', to='music_app.band'),
        ),
    ]
