# Generated by Django 4.1.1 on 2022-10-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0014_alter_album_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='group',
            new_name='band',
        ),
    ]
