# Generated by Django 4.1.1 on 2022-10-12 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0018_alter_band_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)])),
                ('surname', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)])),
                ('comment', models.TextField(max_length=1500, validators=[django.core.validators.MinLengthValidator(10)])),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
