# Generated by Django 4.1.1 on 2022-10-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0023_album_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='comments',
            field=models.ManyToManyField(related_name='albums', to='music_app.commentdb'),
        ),
    ]
