# Generated by Django 4.1.1 on 2022-10-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0024_alter_album_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='comments',
        ),
    ]
