# Generated by Django 4.1.1 on 2022-10-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0026_commentdb_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdb',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='comments', to='music_app.album'),
        ),
    ]
