# Generated by Django 4.1.1 on 2022-10-13 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0027_alter_commentdb_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentdb',
            name='album',
        ),
        migrations.AddField(
            model_name='commentdb',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='music_app.album'),
        ),
    ]
