# Generated by Django 4.1.1 on 2022-10-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0029_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='music_app.genre'),
        ),
    ]
