# Generated by Django 4.1.1 on 2022-10-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0030_band_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='empty'),
        ),
    ]
