# Generated by Django 4.1.1 on 2022-10-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0032_alter_genre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='genre',
        ),
    ]
