# Generated by Django 4.1.2 on 2022-10-26 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0035_album_genres_track_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
