# Generated by Django 4.1.2 on 2022-11-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0037_album_rating_track_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='image',
            field=models.FileField(blank=True, upload_to='img'),
        ),
    ]
